import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useOrganization } from "@/hooks/useOrganization";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Package,Plus } from "lucide-react";
import { toast } from "sonner";

export default function Products(){const {data:org}=useOrganization();const qc=useQueryClient();const [name,setName]=useState("");const [sku,setSku]=useState("");const {data:products=[]}=useQuery({queryKey:["products",org?.organization_id],enabled:!!org,queryFn:async()=>{const {data,error}=await supabase.from("products").select("*").eq("organization_id",org!.organization_id).order("updated_at",{ascending:false});if(error)throw error;return data;}});const add=useMutation({mutationFn:async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user||!org)throw new Error("Non authentifié");const {error}=await supabase.from("products").insert({organization_id:org.organization_id,created_by:auth.user.id,name:name.trim(),sku:sku.trim()||null});if(error)throw error;},onSuccess:()=>{setName("");setSku("");qc.invalidateQueries({queryKey:["products"]});toast.success("Produit mémorisé");}});return <div className="container mx-auto max-w-6xl p-4 md:p-8 space-y-6"><div><p className="text-sm font-semibold text-primary">MÉMOIRE ENTREPRISE</p><h1 className="text-3xl font-bold">Catalogue produits</h1><p className="text-muted-foreground">Réutilisez les descriptions techniques, décisions SH et preuves déjà validées.</p></div><Card><CardHeader><CardTitle className="flex gap-2"><Plus className="h-5 w-5"/>Nouveau produit</CardTitle></CardHeader><CardContent className="flex gap-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nom commercial ou technique"/><Input className="max-w-48" value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU / référence"/><Button disabled={!name.trim()} onClick={()=>add.mutate()}>Ajouter</Button></CardContent></Card><div className="grid gap-4 md:grid-cols-3">{products.length===0?<Card className="md:col-span-3"><CardContent className="py-12 text-center text-muted-foreground"><Package className="mx-auto mb-3 h-10 w-10"/>Le catalogue se construit au fil des dossiers.</CardContent></Card>:products.map(p=><Card key={p.id}><CardHeader><div className="flex justify-between"><CardTitle className="text-base">{p.name}</CardTitle><Badge variant="outline">{p.status}</Badge></div></CardHeader><CardContent><p className="font-mono text-xs text-muted-foreground">{p.sku||"Sans référence interne"}</p><p className="mt-3 text-xs text-muted-foreground">Les versions conservent l’historique des caractéristiques et classifications.</p></CardContent></Card>)}</div></div>}
