import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Scale, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";

export default function AdminLegalVersions(){
  const qc=useQueryClient();const [selected,setSelected]=useState("");
  const {data:versions=[]}=useQuery({queryKey:["legal-versions-review"],queryFn:async()=>{const {data,error}=await supabase.from("legal_versions").select("id,instrument_id,source_document_id,version_label,status,created_at,legal_instruments(canonical_title,official_reference,instrument_type,authority_rank),source_documents(title,lifecycle_status)").order("created_at",{ascending:false}).limit(100);if(error)throw error;return data;}});
  const version=versions.find(item=>item.id===selected);
  const {data:provisions=[]}=useQuery({queryKey:["legal-provisions-review",selected],enabled:!!selected,queryFn:async()=>{const {data,error}=await supabase.from("legal_provisions").select("id,number,heading,body_text,page_start,review_status,hierarchy_path").eq("legal_version_id",selected).order("sequence_number").limit(1000);if(error)throw error;return data;}});
  const validate=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("legal_provisions").update({review_status:"validated"}).eq("id",id);if(error)throw error;},onSuccess:()=>qc.invalidateQueries({queryKey:["legal-provisions-review",selected]}),onError:(error:Error)=>toast.error(error.message)});
  const reject=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.from("legal_provisions").update({review_status:"rejected"}).eq("id",id);if(error)throw error;},onSuccess:()=>qc.invalidateQueries({queryKey:["legal-provisions-review",selected]}),onError:(error:Error)=>toast.error(error.message)});
  const publish=useMutation({mutationFn:async()=>{if(!version)throw new Error("Version introuvable");if(provisions.length===0||provisions.some(p=>p.review_status!=="validated"))throw new Error("Validez chaque article avant publication");const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error("Session expirée");const {error}=await supabase.from("legal_versions").update({status:"published",approved_by:auth.user.id,approved_at:new Date().toISOString()}).eq("id",version.id);if(error)throw error;const {error:instrumentError}=await supabase.from("legal_instruments").update({status:"active"}).eq("id",version.instrument_id);if(instrumentError)throw instrumentError;},onSuccess:()=>{qc.invalidateQueries({queryKey:["legal-versions-review"]});toast.success("Version juridique publiée");},onError:(error:Error)=>toast.error(error.message)});
  const validated=provisions.filter(p=>p.review_status==="validated").length;
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-primary">VALIDATION EXPERTE</p><h1 className="text-3xl font-bold">Versions et articles</h1><p className="text-muted-foreground">Comparez chaque article à sa page source puis publiez seulement une version complète et validée.</p></div><Card><CardHeader><CardTitle>Version juridique</CardTitle></CardHeader><CardContent><Select value={selected} onValueChange={setSelected}><SelectTrigger><SelectValue placeholder="Choisir une version"/></SelectTrigger><SelectContent>{versions.map(v=><SelectItem value={v.id} key={v.id}>{v.legal_instruments?.official_reference||v.version_label} · {v.status}</SelectItem>)}</SelectContent></Select></CardContent></Card>
  {version&&<><Card><CardHeader><CardTitle className="flex gap-2"><Scale className="h-5 w-5"/>{version.legal_instruments?.canonical_title}</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Badge>{version.status}</Badge><Badge variant="outline">Document : {version.source_documents?.lifecycle_status}</Badge><Badge variant="secondary">{validated}/{provisions.length} articles validés</Badge></div><Button disabled={version.status==="published"||publish.isPending||!provisions.length||validated!==provisions.length||version.source_documents?.lifecycle_status!=="published"} onClick={()=>publish.mutate()}><CheckCircle2 className="mr-2 h-4 w-4"/>Publier cette version</Button></CardContent></Card><div className="space-y-3">{provisions.map(p=><Card key={p.id}><CardHeader className="pb-2"><div className="flex justify-between gap-3"><CardTitle className="text-base">{p.heading||`Article ${p.number}`} · page {p.page_start}</CardTitle><Badge variant={p.review_status==="rejected"?"destructive":p.review_status==="validated"?"default":"secondary"}>{p.review_status}</Badge></div></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm max-h-48 overflow-auto">{p.body_text}</p><div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={()=>validate.mutate(p.id)} disabled={p.review_status==="validated"}>Valider</Button><Button size="sm" variant="ghost" onClick={()=>reject.mutate(p.id)} disabled={p.review_status==="rejected"}>Rejeter</Button></div></CardContent></Card>)}</div></>}</div>;
}
