import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";

const MEASURE_TYPES = ["duty", "vat", "tic", "prohibition", "restriction", "authorization", "technical_control", "sanitary_control", "origin_rule", "required_document", "procedure", "exemption", "quota"];

export default function AdminRegulatoryContext() {
  const qc = useQueryClient();
  const [versionId, setVersionId] = useState("");
  const [provisionId, setProvisionId] = useState("");
  const [hsPrefix, setHsPrefix] = useState("");
  const [measureType, setMeasureType] = useState("authorization");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [effectiveFrom, setEffectiveFrom] = useState("");
  const { data: versions = [] } = useQuery({ queryKey: ["context-published-versions"], queryFn: async () => { const { data, error } = await supabase.from("legal_versions").select("id,version_label,legal_instruments(canonical_title,official_reference)").eq("status", "published").order("created_at", { ascending: false }).limit(100); if (error) throw error; return data; } });
  const { data: provisions = [] } = useQuery({ queryKey: ["context-provisions", versionId], enabled: !!versionId, queryFn: async () => { const { data, error } = await supabase.from("legal_provisions").select("id,number,heading,body_text,page_start").eq("legal_version_id", versionId).eq("review_status", "validated").order("sequence_number").limit(1000); if (error) throw error; return data; } });
  const { data: measures = [] } = useQuery({ queryKey: ["context-measures"], queryFn: async () => { const { data, error } = await supabase.from("regulatory_measures").select("id,title,measure_type,hs_prefix,description,validation_status,legal_provision_id,effective_from").order("created_at", { ascending: false }).limit(100); if (error) throw error; return data; } });
  const create = useMutation({ mutationFn: async () => {
    if (!provisionId || !/^[0-9]{2,10}$/.test(hsPrefix) || !title.trim() || description.trim().length < 20) throw new Error("Choisissez un article publié, un préfixe SH de 2 à 10 chiffres et décrivez précisément l'effet de la règle.");
    const { error } = await supabase.from("regulatory_measures").insert({ legal_provision_id: provisionId, hs_prefix: hsPrefix, measure_type: measureType, title: title.trim(), description: description.trim(), effective_from: effectiveFrom || null, country_destination: "MA", validation_status: "proposed" }); if (error) throw error;
  }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["context-measures"] }); setTitle(""); setDescription(""); toast.success("Lien proposé, à valider"); }, onError: (error: Error) => toast.error(error.message) });
  const validate = useMutation({ mutationFn: async (id: string) => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) throw new Error("Session expirée"); const { error } = await supabase.from("regulatory_measures").update({ validation_status: "validated", validated_by: auth.user.id, validated_at: new Date().toISOString() }).eq("id", id).eq("validation_status", "proposed"); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["context-measures"] }); toast.success("Lien réglementaire validé"); }, onError: (error: Error) => toast.error(error.message) });
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-primary">CONTEXTE DOUANIER</p><h1 className="text-3xl font-bold">Règles liées aux codes SH</h1><p className="text-muted-foreground">Reliez chaque obligation, interdiction ou taxe à un article publié et au périmètre SH qu'il couvre.</p></div>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Créer un lien sourcé</CardTitle></CardHeader><CardContent className="space-y-3"><label className="block text-sm">Texte publié<Select value={versionId} onValueChange={(value) => { setVersionId(value); setProvisionId(""); }}><SelectTrigger><SelectValue placeholder="Choisir une version juridique" /></SelectTrigger><SelectContent>{versions.map((version) => <SelectItem key={version.id} value={version.id}>{version.legal_instruments?.official_reference || version.version_label}</SelectItem>)}</SelectContent></Select></label><label className="block text-sm">Article précis<Select value={provisionId} onValueChange={setProvisionId}><SelectTrigger><SelectValue placeholder="Choisir un article validé" /></SelectTrigger><SelectContent>{provisions.map((provision) => <SelectItem key={provision.id} value={provision.id}>{provision.heading || `Article ${provision.number}`} · p. {provision.page_start}</SelectItem>)}</SelectContent></Select></label><label className="block text-sm">Code ou préfixe SH<Input value={hsPrefix} onChange={(event) => setHsPrefix(event.target.value.replace(/\D/g, "").slice(0, 10))} placeholder="Ex. 8703" /></label><label className="block text-sm">Nature de la mesure<Select value={measureType} onValueChange={setMeasureType}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{MEASURE_TYPES.map((type) => <SelectItem key={type} value={type}>{type}</SelectItem>)}</SelectContent></Select></label><label className="block text-sm">Titre<Input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="block text-sm">Effet juridique et conditions<Input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="block text-sm">Date d'effet vérifiée<Input type="date" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} /></label><Button disabled={create.isPending} onClick={() => create.mutate()}>Créer la proposition</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>Liens à contrôler</CardTitle></CardHeader><CardContent className="max-h-[70vh] space-y-3 overflow-auto">{measures.length === 0 && <p className="text-sm text-muted-foreground">Aucune mesure créée.</p>}{measures.map((measure) => <div className="rounded-lg border p-3" key={measure.id}><div className="flex items-start justify-between gap-2"><b>{measure.title}</b><Badge variant={measure.validation_status === "validated" ? "default" : "secondary"}>{measure.validation_status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{measure.measure_type} · SH {measure.hs_prefix} · effet {measure.effective_from || "à préciser"}</p><p className="my-2 text-sm">{measure.description}</p>{measure.validation_status === "proposed" && <Button size="sm" variant="outline" disabled={validate.isPending} onClick={() => validate.mutate(measure.id)}>Valider le lien</Button>}</div>)}</CardContent></Card></div>
  </div>;
}
