import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const relationshipTypes = ["amends", "repeals", "replaces", "implements", "interprets", "complements", "corrects", "suspends", "extends", "references", "creates_exception"];
type Instrument = { id: string; official_reference: string; canonical_title: string; instrument_type: string };

export default function AdminLegalRelationships() {
  const qc = useQueryClient();
  const [sourceSearch, setSourceSearch] = useState("");
  const [targetSearch, setTargetSearch] = useState("");
  const [sourceId, setSourceId] = useState("");
  const [targetId, setTargetId] = useState("");
  const [evidenceId, setEvidenceId] = useState("");
  const [relationshipType, setRelationshipType] = useState("corrects");
  const [effectiveFrom, setEffectiveFrom] = useState("");
  const [evidenceText, setEvidenceText] = useState("");
  const findInstruments = async (search: string): Promise<Instrument[]> => { const { data, error } = await supabase.from("legal_instruments").select("id,official_reference,canonical_title,instrument_type").ilike("official_reference", `%${search.replace(/[%_]/g, "")}%`).order("official_reference").limit(30); if (error) throw error; return data; };
  const { data: sourceResults = [] } = useQuery({ queryKey: ["relationship-source-search", sourceSearch], enabled: sourceSearch.trim().length >= 2, queryFn: () => findInstruments(sourceSearch.trim()) });
  const { data: targetResults = [] } = useQuery({ queryKey: ["relationship-target-search", targetSearch], enabled: targetSearch.trim().length >= 2, queryFn: () => findInstruments(targetSearch.trim()) });
  const { data: versions = [] } = useQuery({ queryKey: ["relationship-source-versions", sourceId], enabled: !!sourceId, queryFn: async () => { const { data, error } = await supabase.from("legal_versions").select("id,version_label").eq("instrument_id", sourceId).eq("status", "published").order("created_at", { ascending: false }); if (error) throw error; return data; } });
  const { data: provisions = [] } = useQuery({ queryKey: ["relationship-source-provisions", versions.map((version) => version.id).join(",")], enabled: versions.length > 0, queryFn: async () => { const all = []; for (const version of versions) { const { data, error } = await supabase.from("legal_provisions").select("id,heading,number,body_text,page_start").eq("legal_version_id", version.id).eq("review_status", "validated").order("sequence_number").limit(1000); if (error) throw error; all.push(...data); } return all; } });
  const { data: relationships = [] } = useQuery({ queryKey: ["legal-relationships-review"], queryFn: async () => { const { data, error } = await supabase.from("legal_relationships").select("id,relationship_type,source_instrument_id,target_instrument_id,effective_from,validation_status,evidence_text").order("created_at", { ascending: false }).limit(100); if (error) throw error; return data; } });
  const create = useMutation({ mutationFn: async () => {
    if (!sourceId || !targetId || !evidenceId || !effectiveFrom || evidenceText.trim().length < 20) throw new Error("Choisissez les deux textes, l'article de preuve, la date d'effet et un extrait justificatif.");
    if (sourceId === targetId) throw new Error("Choisissez deux textes distincts.");
    const { error } = await supabase.from("legal_relationships").insert({ source_instrument_id: sourceId, target_instrument_id: targetId, evidence_provision_id: evidenceId, source_provision_id: evidenceId, relationship_type: relationshipType, effective_from: effectiveFrom, evidence_text: evidenceText.trim(), confidence: 90, validation_status: "proposed" }); if (error) throw error;
  }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["legal-relationships-review"] }); toast.success("Lien juridique proposé pour validation"); }, onError: (error: Error) => toast.error(error.message) });
  const validate = useMutation({ mutationFn: async (id: string) => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) throw new Error("Session expirée"); const { error } = await supabase.from("legal_relationships").update({ validation_status: "validated", validated_by: auth.user.id, validated_at: new Date().toISOString() }).eq("id", id).eq("validation_status", "proposed"); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["legal-relationships-review"] }); toast.success("Relation juridique validée"); }, onError: (error: Error) => toast.error(error.message) });
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-primary">HIÉRARCHIE ET MISES À JOUR</p><h1 className="text-3xl font-bold">Relations entre textes</h1><p className="text-muted-foreground">Une correction ou une abrogation n'a d'effet dans le cerveau douanier qu'après identification du texte source, du texte visé et de la disposition qui le démontre.</p></div>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Créer une relation sourcée</CardTitle></CardHeader><CardContent className="space-y-3"><label className="block text-sm">Texte qui apporte la modification<Input value={sourceSearch} onChange={(event) => setSourceSearch(event.target.value)} placeholder="Rechercher par référence officielle" /></label><select aria-label="Texte source" className="h-10 w-full rounded-md border bg-background px-3" value={sourceId} onChange={(event) => { setSourceId(event.target.value); setEvidenceId(""); }}><option value="">Choisir le texte source</option>{sourceResults.map((item) => <option key={item.id} value={item.id}>{item.official_reference} · {item.instrument_type}</option>)}</select><label className="block text-sm">Texte concerné<Input value={targetSearch} onChange={(event) => setTargetSearch(event.target.value)} placeholder="Rechercher par référence officielle" /></label><select aria-label="Texte cible" className="h-10 w-full rounded-md border bg-background px-3" value={targetId} onChange={(event) => setTargetId(event.target.value)}><option value="">Choisir le texte cible</option>{targetResults.map((item) => <option key={item.id} value={item.id}>{item.official_reference} · {item.instrument_type}</option>)}</select><label className="block text-sm">Article ou disposition justificative</label><select aria-label="Disposition de preuve" className="h-10 w-full rounded-md border bg-background px-3" value={evidenceId} onChange={(event) => { setEvidenceId(event.target.value); setEvidenceText(provisions.find((item) => item.id === event.target.value)?.body_text.slice(0, 1000) || ""); }}><option value="">Choisir une disposition publiée du texte source</option>{provisions.map((item) => <option key={item.id} value={item.id}>{item.heading || item.number || "Disposition"} · p. {item.page_start}</option>)}</select><label className="block text-sm">Nature de la relation</label><select aria-label="Nature de la relation" className="h-10 w-full rounded-md border bg-background px-3" value={relationshipType} onChange={(event) => setRelationshipType(event.target.value)}>{relationshipTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select><label className="block text-sm">Date d'effet vérifiée<Input type="date" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} /></label><label className="block text-sm">Extrait qui prouve la relation<Textarea value={evidenceText} onChange={(event) => setEvidenceText(event.target.value)} rows={5} /></label><Button disabled={create.isPending} onClick={() => create.mutate()}>Créer la proposition</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>Relations récentes</CardTitle></CardHeader><CardContent className="max-h-[70vh] space-y-3 overflow-auto">{relationships.length === 0 && <p className="text-sm text-muted-foreground">Aucune relation juridique créée.</p>}{relationships.map((item) => <div key={item.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><b>{item.relationship_type}</b><Badge variant={item.validation_status === "validated" ? "default" : "secondary"}>{item.validation_status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Effet {item.effective_from || "à vérifier"}</p><p className="my-2 line-clamp-4 text-sm">{item.evidence_text}</p>{item.validation_status === "proposed" && <Button size="sm" variant="outline" disabled={validate.isPending} onClick={() => validate.mutate(item.id)}>Valider avec la preuve</Button>}</div>)}</CardContent></Card></div>
  </div>;
}
